name: Deploy Site And Sync to Gitee

on:
  push:
    branches: [main]

jobs:
  deploy-site-sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm varlet
        run: yarn

      - name: Build site
        run:  yarn dist

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-page
          folder: site
